# Generated by Django 5.1.6 on 2025-03-14 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
